meta_product_name: "Poner"
meta_title: "Poner - Display messages attached to a localisation"
meta_description: "Make each messages more relevant, and get a new experience on sharing messages"
meta_image: "link-fb-1200x630.jpg" # should exist in `app/assets/images/`
