meta_product_name: "Poner"
meta_title: "Poner - Display messages attached to a localisation"
meta_description: "Make each messages more relevant, and get a new experience on sharing messages"
meta_image: "app/assets/images/logo_poner1_1.png" # should exist in `app/assets/images/`
